######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 16 11:39:06 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += news_contents.h py_crawler.h widget.h
SOURCES += main.cpp news_contents.cpp py_crawler.cpp widget.cpp
