######################################################################
# Automatically generated by qmake (2.01a) ? 6? 18 08:27:16 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += news_contents.h py_crawler.h widget.h
SOURCES += main.cpp news_contents.cpp py_crawler.cpp widget.cpp
